name: Test
on: push
jobs:
  tests:
    strategy:
      matrix:
        version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          node-version-file: '.node-version'
      - name: Cache nodenv
        id: cache
        uses: actions/cache@v2
        env: {cache-name: nodenv}
        with:
          path: ~/.nodenv
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: Install nodenv
        run: git clone https://github.com/nodenv/nodenv.git ~/.nodenv
      - name: Install modules
        run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test --json --outputFile=result.json --testLocationInResults
      - uses: ./
        if: always()
        with:
          action-name: jest report (${{ matrix.version }})
          github-token: ${{ secrets.GITHUB_TOKEN }}
